version: '2'
services:
    liam2-php-apache:
        build:
            context: ./_bpmspace_base
        restart: always
        hostname: LIAM2-Server
        ports:
            - EXT_PORT_LIAM2_HTTP:80
            - EXT_PORT_LIAM2_HTTPS:443
        volumes:
            - LIAM2-www-data:/var/www/html
            - LIAM2-www-config:/root/config
        links:
            - 'mariadb'
        networks:
            testing_net:
                ipv4_address: IP_LIAM2

    liam2-client-php-apache:
        build:
            context: ./_bpmspace_base
        restart: always
        hostname: LIAM2-CLIENT
        ports:
            - EXT_PORT_LIAM2_CLIENT_HTTP:80
            - EXT_PORT_LIAM2_CLIENT_HTTPS:443
        volumes:
            - LIAM2-CLIENT-www-data:/var/www/html
            - LIAM2-CLIENT-www-config:/root/config
        networks:
            testing_net:
                ipv4_address: IP_LIAM2_CLIENT
         
    mariadb:
        image: mariadb:10.1
        restart: always
        hostname: MARIADB-Server
        ports:
            - MARIADB_EXT_PORT_SQL:3306
        volumes:
            - mariadb:/var/lib/mysql
            - mariadb_config:/root/config
        environment:
            TZ: "Europe/Rome"
            MYSQL_ALLOW_EMPTY_PASSWORD: "no"
            MYSQL_ROOT_PASSWORD: "MARIADB_ROOT_PASSWD"
        entrypoint:
            sh -c "echo '
            CREATE DATABASE IF NOT EXISTS LIAM2_DB_NAME; 
            ' > /docker-entrypoint-initdb.d/init.sql ;
            /usr/local/bin/docker-entrypoint.sh --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci"
        networks:
            testing_net:
                ipv4_address: MARIADB_IP
                
    mailhog:
        container_name: mailhog
        hostname: MAIL-Server
        image: mailhog/mailhog
        restart: always
        ports:
            - EXT_PORT_MAILHOG_SMPT:1025
            - EXT_PORT_MAILHOG_HTTP:8025
        networks:
            testing_net:
                ipv4_address: IP_MAILHOG
                
volumes:
    mariadb:
        external:
            name: PREFIX-mariadb-data
    mariadb_config:
        external:
            name: PREFIX-mariadb-config
             
    LIAM2-www-data:
        external:
            name: PREFIX-LIAM2-www-data
    LIAM2-www-config:
        external:
            name: PREFIX-LIAM2-www-config
            
    LIAM2-CLIENT-www-data:
        external:
            name: PREFIX-LIAM2-CLIENT-www-data
    LIAM2-CLIENT-www-config:
        external:
            name: PREFIX-LIAM2-CLIENT-www-config

networks:
    testing_net:
        ipam:
            driver: default
            config:
                - subnet: DOCKERNETWORK/DOCKERNETMASK
                