version: '3.7'
services:
    server:
        image: richarvey/nginx-php-fpm:latest
        restart: always
        hostname: ${var_server_name}
        container_name: ${var_server_name}
        environment:  
          - VIRTUAL_HOST=${var_server_name}  
networks:
  default:
    external:
      name: nginx-proxy-${var_network_suffix}