version: '2'
services:
  nginx-proxy:
    hostname: nginx-proxy
    container_name: nginx-proxy
    image: jwilder/nginx-proxy
    ports:
        - "${var_http_proxport}:80"
    volumes:
        - /var/run/docker.sock:/tmp/docker.sock:ro
networks:
    default:
      external:
        name: nginx-proxy
