version: '2'
services:
  nginx-proxy-notlive:
    hostname: nginx-proxy-notlive
    container_name: nginx-proxy-notlive
    image: jwilder/nginx-proxy
    ports:
        - "${var_http_proxyport_notlive}:80"
    volumes:
        - /var/run/docker.sock:/tmp/docker.sock:ro
networks:
    default:
      external:
        name: nginx-proxy-notlive
