version: '3.7'
services:
services:
    apms2-php-apache:
    build:
    context: ./_bpmspace_base
    restart: always
    hostname: asms2-${var_server_name}
    container_name: asms2-${var_server_name}
    environment:  
    - VIRTUAL_HOST=$asms2-{var_server_name}
    - NODE_ENV=${var_environment_i}
networks:
  default:
    external:
      name: nginx-proxy-${var_network_suffix}