version: '2'
services:
         
    mariadb:
        image: mariadb:10.1
        hostname: MARIADB_TEMP-Server
        container_name: MARIADB_TEMP-Server
        ports:
            - MARIADB_EXT_PORT_SQL:3306
        environment:
            TZ: "Europe/Rome"
            MYSQL_ALLOW_EMPTY_PASSWORD: "no"
            MYSQL_ROOT_PASSWORD: "MARIADB_ROOT_PASSWD"

        networks:
            testing_net:
                ipv4_address: MARIADB_IP
networks:
    testing_net:
        ipam:
            driver: default
            config:
                - subnet: DOCKERNETWORK/DOCKERNETMASK