version: '2'
services:
 helloworld:
  hostname: ${var_server_name}
  container_name: ${var_server_name}
  image: jwilder/whoami
  environment:  
    - VIRTUAL_HOST=${var_server_name}
    - VIRTUAL_PORT=${var_http_port}
    - NODE_ENV=${var_environment_i}
    
networks:
  default:
    external:
      name: nginx-proxy